---
title: "Storyboard"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---

### K-pop, J-pop and Western {.tabset}

```{r}
library(ggplot2)
library(tidyverse)
library(spotifyr)
library(extrafont)
library(plotly)
# Change to Georgia font family pls
musicology <- get_playlist_audio_features("", "4qytaIOVyWpUF2ncTXkjLZ") %>%
  mutate(artist.name = map_chr(track.artists, function(x) x$name[1])) %>%
  mutate(valence_factor = round(valence))
```

```{r}
# plot with energy and danceability
energy_dance <- ggplot(musicology, aes(energy, danceability, color = artist.name)) +
  geom_point(size = 5, alpha = 0.4) +
  theme(text = element_text(family = "Bookman", color = "Gray25")) +
  labs(title = "Artists show different distributions in energy and danceability",
       y = "Danceability", 
       x = "Energy",
       subtitle = "The Script shows a lot of diversity") +
  guides(color = guide_legend(title = "Artist"))
energy_dance
#ggplotly(energy_dance) %>%
#  layout(showlegend = TRUE)
```

***
This is where two other plots are shown

```{r, fig.width=3, fig.height=3}
ggplot(musicology, aes(factor(mode), fill = artist.name)) +
  geom_bar(position = position_dodge()) +
  theme(text = element_text(family = "Bookman", color = "Gray25")) +
  labs(title = "Mode of every track",
       y = "Count", 
       x = "Mode",
       subtitle = "The data mainly has tracks with major modality") +
  guides(color = guide_legend(title = "Artist"), fill = guide_legend("Artist"), linetype = guide_legend("Artist")) +
  ylim(0, 15)
```
```{r fig.width=3, fig.height=3}
ggplot(musicology, aes(factor(valence_factor), fill = artist.name)) +
  geom_bar(position = position_dodge()) +
  theme(text = element_text(family = "Bookman", color = "Gray25")) +
  labs(title = "Valence of all tracks",
       y = "Count", 
       x = "Valence",
       subtitle = "Many tracks are more negative than positive in emotion") +
  guides(color = guide_legend(title = "Artist"), fill = guide_legend("Artist"), linetype = guide_legend("Artist")) +
  ylim(0, 15)
```

### Differences between western and eastern music

```{r}
```

We'll see...

### What makes each region's music unique

```{r}
```

If you see this that means I succeeded